<?php if ($block->isActive()): ?>
    <?php if ($block->isSandbox()): ?>
        <?php $url = "https://test-hpf.novattipayments.com/js/v1.0/hosted-fields"; ?>
    <?php else: ?>
        <?php $url = "https://hpf.novattipayments.com/js/v1.0/hosted-fields"; ?>
    <?php endif; ?>
    <script>
        require.config({
            paths: {
                'HPF': '<?php echo $url ?>'
            },
            shim: {
                'HPF': {
                    exports: 'HPF'
                }
            }
        });
    </script>
    <script type="text/javascript">
        //<![CDATA[ 
        (function() {
        function riskifiedBeaconLoad() {
            var store_domain = '<?= $block->getRiskifiedDomain() ?>';
            var session_id = '<?= $block->getQuoteId() ?>';
            var url = ('https:' == document.location.protocol ? 'https://' : 'http://')
            + "beacon.riskified.com?shop=" + store_domain + "&sid=" + session_id;
            var s = document.createElement('script');
            s.type = 'text/javascript';
            s.async = true;
            s.src = url;
            var x = document.getElementsByTagName('script')[0];
            x.parentNode.insertBefore(s, x);
        }
        if (window.attachEvent)
            window.attachEvent('onload', riskifiedBeaconLoad)
        else
            window.addEventListener('load', riskifiedBeaconLoad, false);
        })();
        //]]>

        window.setTimeout( function() {
            window.location.reload();
        }, 900000);
    </script>
<?php endif; ?>